# This is the network config written by 'subiquity'
network:
  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - 192.168.1.125/24
      gateway4: 192.168.1.10
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
    # enx000ec6c61e15:
    #   dhcp4: no
    #   addresses:
    #     - 192.168.3.1/24
    #     - 192.168.3.2/24
    #   gateway4: 192.168.3.1
    #   nameservers:
    #     addresses: [8.8.8.8, 1.1.1.1]

  version: 2

  