---


- hosts: provisioner
  become: yes
  vars:
    - copy_osie: true
  tasks:
  - name: Install dependencies
    apt:
      name: 
        - docker
        - docker-compose
        - jq
        - ifupdown
      state: present
  
  # - name: Copy OSIE
  #   copy:
  #     src: osie.tar.gz
  #     dest: /root/osie.tar.gz
  #   when: copy_osie

  - name: Git checkout 
    git:
      repo: 'https://github.com/tinkerbell/sandbox.git'
      dest: /root/sandbox
      force: yes
      version: v0.4.0

  - name: Generate envrc 
    shell: 
      cmd: ./generate-envrc.sh {{ network_interface }} > envrc
      chdir: /root/sandbox

  - name: Add OSIE file location to envrc
    shell: 
      cmd: echo 'export TB_OSIE_TAR=/root/osie.tar.gz' >> envrc
      chdir: /root/sandbox
    when: copy_osie
  
  - name: Prepare envrc
    shell: 
      cmd: sed -i 's/192.168.1/192.168.3/g' envrc
      chdir: /root/sandbox

  - name: Prepare .env 
    shell: 
      cmd: cat envrc | sed 's/export //g' > .env
      chdir: /root/sandbox

  - name: Run setup
    shell: 
      cmd: . ./envrc && ./setup.sh
      chdir: /root/sandbox

  - name: docker-compose up
    shell: 
      cmd: . ../envrc && docker-compose down && docker-compose up --force-recreate -d
      chdir: /root/sandbox/deploy


