- hosts: provisioner
  become: yes
  tasks:
  - include: helper_tasks/add_template.yml
    vars:
        template_name: "{{ item | basename | splitext | first }}"
    with_fileglob:
    - "templates/*.tmpl"
